openapi: "3.0.3"
info:
  description: "New Relic Challenge API"
  version: "1.0.0"
  title: "New Relic Challenge API"
servers:
  - url: https://localhost:8080/api/v1
    description: "local"

tags:
  - name: newrelic

paths:
  '/wordsCount':
    post:
      tags:
        - newrelic
      summary: Find 100 of most common three word sequences in descending order
      operationId: processFileAndCountThreeWords
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WordsCountRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WordsCountResponse"
components:
  schemas:
    WordsCountRequest:
      type: object
      properties:
        fileNames:
          type: array
          items:
            type: string
    WordsCountResponse:
      type: object
      properties:
        fileName:
          type: string
        wordsAndCount:
          type: array
          items:
            $ref: "#/components/schemas/KeyValuePair"
    KeyValuePair:
      type: object
      properties:
        word:
          type: string
        count:
          type: integer
